name: Release

on:
  push:
    tags: v*.*.*

env:
  BIN_NAME: AMDlert
  PLATFORM: windows-x64
  TAG: ${{ github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: extractions/setup-just@v4

      - run: just lint
      - run: just build

      - run: |
          REPO=${{ github.event.repository.name }}
          VER=${TAG#v}
          BIN=target/release/$BIN_NAME.exe
          OUT=dist/$BIN_NAME
          ZIP=dist/$REPO-$VER-$PLATFORM.zip

          mkdir -p $OUT
          cp $BIN $OUT
          python3 -m zipfile -c $ZIP $OUT

      - run: gh release create --title $TAG --draft $TAG dist/*.zip
        env:
          GH_TOKEN: ${{ github.token }}
